### ISSUE TITLE
Forum topic in KSP2 Mod Release forum

### ISSUE THREAD

**Issue by schlosrat** [Halbann/LazyOrbit#7]
Please create a forum topic in the KSP2 forum where you can alert users to updates, and users can ask questions, etc.

https://forum.kerbalspaceprogram.com/index.php?/forum/130-ksp2-mod-releases/

**Comment by Halbann** [comment]
Done!

https://forum.kerbalspaceprogram.com/index.php?/topic/214571-lazy-orbit-v040-set-a-vessels-orbit-via-a-simple-menu/#comment-4253292
